; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26131.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\8587903\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
